"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ro';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Login
    'welcome_back': 'Welcome back! Please sign in to your account.',
    'username': 'Username',
    'password': 'Password',
    'sign_in': 'Sign in',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'demo_credentials': 'Demo Credentials:',
    'signing_in': 'Signing in...',
    'cars_service': 'CARS & SERVICE',
    'username_placeholder': 'Enter your username',
    'password_placeholder': 'Enter your password',
    'invalid_credentials': 'Invalid credentials. Use admin/BYE9438x_# for demo.',
    'demo_username': 'Username',
    'demo_password': 'Password',

    // Dashboard
    'dashboard': 'Dashboard',
    'overview': 'Overview',
    'welcome_message': 'Welcome back! Here\'s what\'s happening with your fleet.',
    'vehicles_in_service': 'Vehicles in Service',
    'avg_repair_time': 'Avg Repair Time',
    'repairs_in_progress': 'Repairs in Progress',
    'monthly_revenue': 'Monthly Revenue',
    'this_week': 'this week',
    'vs_last_week': 'vs last week',
    'vs_last_month': 'vs last month',
    'bmw_service_management': 'BMW Service Management',
    'bmw_service_description': 'Service auto dedicat BMW cu experiența - reparatii, întreținere - electrica și mecanică!',
    'recent_activity': 'Recent Activity',
    'quick_actions': 'Quick Actions',
    'add_new_vehicle': 'Add New Vehicle',
    'create_repair_order': 'Create Repair Order',
    'client_portal': 'Client Portal',
    'system_quote': 'System Quote',
    'welcome_back_bye_auto': 'Welcome back, BYE AUTO',

    // Vehicle Status
    'in_service': 'In Service',
    'waiting': 'Waiting',
    'completed': 'Completed',
    'diagnostic': 'Diagnostic',
    'high_priority': 'High',
    'medium_priority': 'Medium',
    'low_priority': 'Low',
    'active_repairs': 'Active Repairs',
    'scheduled': 'Scheduled',
    'ready_for_delivery': 'Ready for Delivery',
    'urgent': 'Urgent',

    // Navigation
    'vehicles': 'Vehicles',
    'repairs': 'Repairs',
    'clients': 'Clients',
    'analytics': 'Analytics',
    'settings': 'Settings',
    'messages': 'Messages',
    'tuning_services': 'Tuning Services',

    // Vehicles Page
    'manage_bmw_fleet': 'Manage your BMW fleet',
    'add_vehicle': 'Add Vehicle',
    'search_vehicles_placeholder': 'Search vehicles by license plate, client, or model...',
    'all_status': 'All Status',
    'active': 'Active',
    'maintenance': 'Maintenance',
    'license_plate': 'License Plate',
    'client': 'Client',
    'mileage': 'Mileage',
    'last_service': 'Last Service',
    'next_service': 'Next Service',
    'view': 'View',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'vehicle_details': 'Vehicle Details',
    'edit_vehicle': 'Edit Vehicle',
    'make': 'Make',
    'model': 'Model',
    'year': 'Year',
    'status': 'Status',
    'no_vehicles_found': 'No vehicles found',
    'try_adjusting_search': 'Try adjusting your search or filter criteria.',

    // Tune Page
    'bmw_tuning_services': 'BMW Tuning Services',
    'tuning_description': 'Professional ECU tuning and performance upgrades',
    'find_your_vehicle': 'Find Your Vehicle',
    'license_placeholder': 'e.g., DB 99BYE',
    'license_help': 'Enter your license plate to find tuning options',
    'find_tuning_options': 'Find Tuning Options',
    'searching': 'Searching...',
    'example': 'Example:',
    'vehicle_information': 'Vehicle Information',
    'vehicle': 'Vehicle',
    'engine': 'Engine',
    'current_power': 'Current Power',
    'current_torque': 'Current Torque',
    'transmission': 'Transmission',
    'tuning_packages': 'Tuning Packages',
    'power_gain': 'Power Gain',
    'torque_gain': 'Torque Gain',
    'duration': 'Duration',
    'warranty': 'Warranty',
    'select_package': 'Select Package',
    'features': 'Features',
    'performance_summary': 'Performance Summary',
    'after_tuning': 'After Tuning',
    'additional_parts': 'Additional Performance Parts',
    'add_to_quote': 'Add to Quote',
    'bmw_tuning_wizard': 'BMW Tuning Wizard',
    'bmw_wizard_description': 'Don\'t have a license plate? Use our step-by-step BMW tuning wizard to find the perfect upgrade for your BMW.',
    'start_bmw_wizard': 'Start BMW Tuning Wizard',

    // Notifications
    'system_online': 'System Online',
    'system_online_message': 'BMW Service Management System is running smoothly',
    'new_messages': 'New Messages',
    'new_messages_text': 'You have 2 unread messages in your inbox',
    'maintenance_due': 'Maintenance Due',
    'maintenance_due_message': 'Vehicle B-123-ABC needs service in 3 days',
    'test_notification': 'Test Notification',
    'test_notification_message': 'This is a test notification from the dashboard',
    'test_notifications': 'Test Notifications',

    // Recent Activity
    'bmw_x5_repair_completed': 'BMW X5 Repair Completed',
    'engine_diagnostic_finished': 'Engine diagnostic and electrical system repair finished',
    'new_bmw_320i_arrived': 'New BMW 320i Arrived',
    'client_maria_brake_inspection': 'Client Maria Ionescu - brake system inspection needed',
    'urgent_repair_alert': 'Urgent Repair Alert',
    'bmw_x3_transmission_inspection': 'BMW X3 requires immediate transmission inspection',
    '1_hour_ago': '1 hour ago',
    '3_hours_ago': '3 hours ago',
    '5_hours_ago': '5 hours ago',

    // Quote Page
    'view_special_proposal': 'View Special Proposal',
    'complete_solution_proposal': 'BYE Auto - Complete Solution Proposal',
    'system_development_bmw_project': 'System Development + BMW F32 420d N47 Stage 2+ Project',
    'system_development': 'System Development',
    'bmw_project': 'BMW Project',
    'bmw_service_management_system': 'BMW Service Management System',
    'bmw_f32_stage2_title': 'BMW F32 420d N47 – STAGE 2+ / MAX PERFORMANCE BUILD',
    'goal': 'Goal',
    'required_upgrades': 'Required Upgrades',
    'expected_results': 'Expected Results',
    'estimated_budget': 'Estimated Budget',
    'client_notes': 'Client Notes',
    'core_features': 'Core Features',
    'advanced_features': 'Advanced Features',
    'enhancements': 'Enhancements',
    'performance_upgrades': 'Performance Upgrades',
    'preventive_work': 'Preventive Work',
    'm4_look_quad': 'M4-Look & Quad Exhaust',
    'annual_maintenance': 'Annual Maintenance',
    'total_investment': 'Total Investment',
    'includes_maintenance': 'Includes annual maintenance and support',
    'technology_stack': 'Technology Stack',
    'deployment': 'Deployment',
    'support_maintenance': 'Support & Maintenance',
    
    // Quote Page - Special Proposal
    'special_partnership_proposal': 'Special Partnership Proposal',
    'what_youre_looking_at': 'What You\'re Looking At',
    'two_separate_proposals': 'This quote page contains two separate proposals:',
    'system_development_desc': 'System Development - Complete BMW service management system',
    'bmw_project_desc': 'BMW F32 420d Project - Stage 2+ performance build with M4-look & quad exhaust for your car',
    'our_special_proposal': 'Our Special Proposal',
    'mutual_exchange_desc': 'Instead of paying for each service separately, we propose a mutual exchange:',
    'what_i_do_for_you': 'What I Do For You',
    'develop_system_free': 'Develop and deploy the complete BMW service management system FREE OF CHARGE',
    'what_you_do_for_me': 'What You Do For Me',
    'perform_build_free': 'Perform the complete BMW F32 420d Stage 2+ build FREE OF CHARGE',
    'win_win_partnership': 'Win-Win Partnership',
    'partnership_proposal_desc': 'This is a partnership proposal where both parties benefit equally. No money changes hands - just mutual value exchange.',
    
    // Quote Page - System Features
    'bmw_service_dashboard': 'BMW Service Dashboard',
    'dashboard_desc': 'Complete repair management system with real-time tracking',
    'client_portal_desc': 'License plate lookup, VIN search, and vehicle specifications',
    'quote_system': 'Quote System',
    'quote_system_desc': 'Automated quote generation and management',
    'bye_auto_website': 'BYE Auto Website',
    'website_desc': 'Professional company website with services, tuning options, and booking system',
    'analytics_reports': 'Analytics & Reports',
    'analytics_desc': 'Business intelligence and performance tracking',
    'mobile_application': 'Mobile Application',
    'mobile_app_desc': 'iOS and Android apps for field operations',
    'api_integration': 'API Integration',
    'api_desc': 'Third-party integrations and data synchronization',
    'multi_language_support': 'Multi-language Support',
    'multi_lang_desc': 'English, Romanian, and Dutch language support',
    'backup_security': 'Backup & Security',
    'backup_desc': 'Automated backups and advanced security features',
    
    // Quote Page - BMW Project
    'vehicle_info': 'Vehicle',
    'vehicle_desc': 'BMW 420d F32 (N47 engine, 184 hp stock)',
    'goal_desc': 'Reliable Stage 2+/3 upgrade to ±270–280 hp / ±580–600 Nm',
    'power': 'Power',
    'torque': 'Torque',
    'acceleration': 'Acceleration',
    'reliability': 'Reliability',
    'budget_note': 'Note: Prices may vary based on specific requirements and market conditions',
    
    // Quote Page - System Overview
    'complete_system_overview': 'Complete BYE Auto System Overview',
    'admin_dashboard_functions': 'Admin Dashboard Functions',
    'vehicle_management': 'Vehicle Management (Add, Edit, Delete)',
    'repair_order_management': 'Repair Order Management',
    'client_database_history': 'Client Database & History',
    'real_time_analytics': 'Real-time Analytics & Reports',
    'whatsapp_integration': 'WhatsApp Business Integration',
    'multi_lang_support_dashboard': 'Multi-language Support (EN/RO)',
    'automated_quotes': 'Automated Quote Generation',
    'inventory_management': 'Inventory Management',
    'website_functions': 'BYE Auto Website Functions',
    'company_information': 'Company Information & About',
    'bmw_services': 'BMW Service & Repair Services',
    'tuning_options': 'Performance Tuning Options',
    'online_booking': 'Online Booking System',
    'license_lookup': 'License Plate Lookup Tool',
    'contact_form': 'Contact Form & Location',
    'customer_reviews': 'Customer Reviews & Gallery',
    'mobile_responsive': 'Mobile Responsive Design',
    'tuning_services_integration': 'Performance Tuning Services (Website Integration)',
    'stage_1_tuning': 'Stage 1 Tuning',
    'stage_1_desc': 'Software optimization for stock hardware',
    'stage_2_tuning': 'Stage 2 Tuning',
    'stage_2_desc': 'Software + basic hardware upgrades',
    'stage_3_tuning': 'Stage 3+ Tuning',
    'stage_3_desc': 'Complete performance build with custom hardware',
    'power_increase': 'Power Increase',

    // Work Management
    'work_management': 'Work Management',
    'workshop_dashboard': 'Workshop Dashboard',
    'remaining_work_hours': 'Remaining Work Hours',
    'expected_completion': 'Expected Completion',
    'overtime_alert': 'Overtime Alert',
    'today': 'Today',
    'normal_time': 'Normal Time',
    'working_status': 'Working Status',
    'working': 'Working',
    'outside_work_hours': 'Outside Work Hours',
    'remaining_work': 'Remaining Work',
    'expected_finish': 'Expected Finish',
    'waiting_items': 'Waiting Items',
    'overtime_needed': 'Overtime Needed',
    'overtime_until': 'Overtime Until',
    'plan_extra_time': 'Plan Extra Time!',
    'on_schedule': 'On Schedule',
    'no_overtime_needed': 'No Overtime Needed',
    'total_work': 'Total Work',
    'ready': 'Ready',
    'in_progress': 'In Progress',
    'team': 'Team',
    'tasks': 'tasks',
    'efficiency': 'Efficiency',
    'average_time': 'Average Time',
    'time_saved': 'Time Saved',
    'customer_satisfaction': 'Customer Satisfaction',
    'pending': 'Pending',
    'assigned_to': 'Assigned To',
    'estimated_time': 'Estimated Time',
    'started_at': 'Started At',
    'work_type': 'Work Type',
    'new_task': 'New Task',
    'edit_task': 'Edit Task',
    'delete_task': 'Delete Task',
    'start': 'Start',
    'finish': 'Finish',
    'restart': 'Restart',
    'back': 'Back',
    'add': 'Add',
    'select_team_member': 'Select Team Member',
    'estimated_time_placeholder': 'e.g. 2h',
    'confirm_delete': 'Are you sure you want to delete this task?',

    // Opening Hours
    'opening_hours': 'Opening Hours',
    'business_hours': 'Business Hours',
    'set_all_days': 'Set All Days 08:00-18:00',
    'weekdays_only': 'Weekdays Only',
    'close_all_days': 'Close All Days',
    'save_opening_hours': 'Save Opening Hours',
    'closed': 'Closed',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',

    // Work Hours & Overtime
    'work_end_time': 'Work End Time',
    'overtime_required': 'Overtime Required',
    'work_until': 'Work Until',
    'hours_overtime': 'hours overtime',
    'today_schedule': 'Today\'s Schedule',

    // Common
    'close': 'Close',
    'logout': 'Logout',
    'language': 'Language',
    'english': 'English',
    'romanian': 'Romanian'
  },
  ro: {
    // Login
    'welcome_back': 'Bun venit! Vă rugăm să vă conectați la contul dvs.',
    'username': 'Nume utilizator',
    'password': 'Parolă',
    'sign_in': 'Conectare',
    'remember_me': 'Ține-mă minte',
    'forgot_password': 'Ai uitat parola?',
    'demo_credentials': 'Credențiale Demo:',
    'signing_in': 'Se conectează...',
    'cars_service': 'MAȘINI & SERVICE',
    'username_placeholder': 'Introduceți numele de utilizator',
    'password_placeholder': 'Introduceți parola',
    'invalid_credentials': 'Credențiale invalide. Folosiți admin/BYE9438x_# pentru demo.',
    'demo_username': 'Nume utilizator',
    'demo_password': 'Parolă',

    // Dashboard
    'dashboard': 'Dashboard',
    'overview': 'Prezentare generală',
    'welcome_message': 'Bun venit înapoi! Iată ce se întâmplă cu flota ta.',
    'vehicles_in_service': 'Vehicule în Service',
    'avg_repair_time': 'Timp Mediu Reparație',
    'repairs_in_progress': 'Reparații în Curs',
    'monthly_revenue': 'Venit Lunar',
    'this_week': 'această săptămână',
    'vs_last_week': 'vs săptămâna trecută',
    'vs_last_month': 'vs luna trecută',
    'bmw_service_management': 'Management Service BMW',
    'bmw_service_description': 'Service auto dedicat BMW cu experiența - reparatii, întreținere - electrica și mecanică!',
    'recent_activity': 'Activitate Recentă',
    'quick_actions': 'Acțiuni Rapide',
    'add_new_vehicle': 'Adaugă Vehicul Nou',
    'create_repair_order': 'Creează Comandă Reparație',
    'client_portal': 'Portal Client',
    'system_quote': 'Ofertă Sistem',
    'welcome_back_bye_auto': 'Bun venit înapoi, BYE AUTO',

    // Vehicle Status
    'in_service': 'În Service',
    'waiting': 'În Așteptare',
    'completed': 'Finalizat',
    'diagnostic': 'Diagnostic',
    'high_priority': 'Înaltă',
    'medium_priority': 'Medie',
    'low_priority': 'Scăzută',
    'active_repairs': 'Reparații Active',
    'scheduled': 'Programat',
    'ready_for_delivery': 'Gata de Livrare',
    'urgent': 'Urgent',

    // Navigation
    'vehicles': 'Vehicule',
    'repairs': 'Reparații',
    'clients': 'Clienți',
    'analytics': 'Analiză',
    'settings': 'Setări',
    'messages': 'Mesaje',
    'tuning_services': 'Servicii Tuning',

    // Vehicles Page
    'manage_bmw_fleet': 'Gestionează flota ta BMW',
    'add_vehicle': 'Adaugă Vehicul',
    'search_vehicles_placeholder': 'Caută vehicule după număr înmatriculare, client sau model...',
    'all_status': 'Toate Statusurile',
    'active': 'Activ',
    'maintenance': 'Întreținere',
    'license_plate': 'Număr Înmatriculare',
    'client': 'Client',
    'mileage': 'Kilometraj',
    'last_service': 'Ultimul Service',
    'next_service': 'Următorul Service',
    'view': 'Vezi',
    'edit': 'Editează',
    'delete': 'Șterge',
    'save': 'Salvează',
    'cancel': 'Anulează',
    'vehicle_details': 'Detalii Vehicul',
    'edit_vehicle': 'Editează Vehicul',
    'make': 'Marcă',
    'model': 'Model',
    'year': 'An',
    'status': 'Status',
    'no_vehicles_found': 'Nu s-au găsit vehicule',
    'try_adjusting_search': 'Încercați să ajustați criteriile de căutare sau filtrare.',

    // Tune Page
    'bmw_tuning_services': 'Servicii Tuning BMW',
    'tuning_description': 'Tuning ECU profesional și upgrade-uri performanță',
    'find_your_vehicle': 'Găsește Vehiculul Tău',
    'license_placeholder': 'ex., DB 99BYE',
    'license_help': 'Introduceți numărul de înmatriculare pentru a găsi opțiunile de tuning',
    'find_tuning_options': 'Găsește Opțiuni Tuning',
    'searching': 'Se caută...',
    'example': 'Exemplu:',
    'vehicle_information': 'Informații Vehicul',
    'vehicle': 'Vehicul',
    'engine': 'Motor',
    'current_power': 'Putere Actuală',
    'current_torque': 'Cuplu Actual',
    'transmission': 'Transmisie',
    'tuning_packages': 'Pachete Tuning',
    'power_gain': 'Creștere Putere',
    'torque_gain': 'Creștere Cuplu',
    'duration': 'Durată',
    'warranty': 'Garanție',
    'select_package': 'Selectează Pachet',
    'features': 'Caracteristici',
    'performance_summary': 'Rezumat Performanță',
    'after_tuning': 'După Tuning',
    'additional_parts': 'Piese Performanță Suplimentare',
    'add_to_quote': 'Adaugă la Ofertă',
    'bmw_tuning_wizard': 'Asistent Tuning BMW',
    'bmw_wizard_description': 'Nu aveți număr de înmatriculare? Folosiți asistentul nostru pas cu pas pentru tuning BMW pentru a găsi upgrade-ul perfect pentru BMW-ul dvs.',
    'start_bmw_wizard': 'Pornește Asistentul BMW',

    // Notifications
    'system_online': 'Sistem Online',
    'system_online_message': 'Sistemul de Management Service BMW funcționează perfect',
    'new_messages': 'Mesaje Noi',
    'new_messages_text': 'Aveți 2 mesaje necitite în inbox',
    'maintenance_due': 'Întreținere Scadentă',
    'maintenance_due_message': 'Vehiculul B-123-ABC necesită service în 3 zile',
    'test_notification': 'Notificare Test',
    'test_notification_message': 'Aceasta este o notificare de test de pe dashboard',
    'test_notifications': 'Test Notificări',

    // Recent Activity
    'bmw_x5_repair_completed': 'Reparație BMW X5 Finalizată',
    'engine_diagnostic_finished': 'Diagnostic motor și reparație sistem electric finalizate',
    'new_bmw_320i_arrived': 'BMW 320i Nou Sosit',
    'client_maria_brake_inspection': 'Client Maria Ionescu - inspecție sistem frână necesară',
    'urgent_repair_alert': 'Alertă Reparație Urgentă',
    'bmw_x3_transmission_inspection': 'BMW X3 necesită inspecție transmisie imediată',
    '1_hour_ago': 'acum 1 oră',
    '3_hours_ago': 'acum 3 ore',
    '5_hours_ago': 'acum 5 ore',

    // Quote Page
    'view_special_proposal': 'Vezi Propunerea Specială',
    'complete_solution_proposal': 'BYE Auto - Propunere Soluție Completă',
    'system_development_bmw_project': 'Dezvoltare Sistem + Proiect BMW F32 420d N47 Stage 2+',
    'system_development': 'Dezvoltare Sistem',
    'bmw_project': 'Proiect BMW',
    'bmw_service_management_system': 'Sistem Management Service BMW',
    'bmw_f32_stage2_title': 'BMW F32 420d N47 – STAGE 2+ / CONSTRUCȚIE PERFORMANȚĂ MAXIMĂ',
    'goal': 'Obiectiv',
    'required_upgrades': 'Upgrade-uri Necesare',
    'expected_results': 'Rezultate Așteptate',
    'estimated_budget': 'Buget Estimativ',
    'client_notes': 'Note Client',
    'core_features': 'Funcții de Bază',
    'advanced_features': 'Funcții Avansate',
    'enhancements': 'Îmbunătățiri',
    'performance_upgrades': 'Upgrade-uri Performanță',
    'preventive_work': 'Lucrări Preventive',
    'm4_look_quad': 'M4-Look & Eșapament Quad',
    'annual_maintenance': 'Întreținere Anuală',
    'total_investment': 'Investiție Totală',
    'includes_maintenance': 'Include întreținere anuală și suport',
    'technology_stack': 'Stack Tehnologie',
    'deployment': 'Implementare',
    'support_maintenance': 'Suport & Întreținere',
    
    // Quote Page - Special Proposal
    'special_partnership_proposal': 'Propunere Parteneriat Special',
    'what_youre_looking_at': 'Ce Vedeți Aici',
    'two_separate_proposals': 'Această pagină de ofertă conține două propuneri separate:',
    'system_development_desc': 'Dezvoltare Sistem - Sistem complet de management service BMW',
    'bmw_project_desc': 'Proiect BMW F32 420d - Construcție performanță Stage 2+ cu look M4 și eșapament quad pentru mașina ta',
    'our_special_proposal': 'Propunerea Noastră Specială',
    'mutual_exchange_desc': 'În loc să plătiți pentru fiecare serviciu separat, propunem un schimb mutual:',
    'what_i_do_for_you': 'Ce Fac Pentru Tine',
    'develop_system_free': 'Dezvolt și implementez sistemul complet de management service BMW GRATUIT',
    'what_you_do_for_me': 'Ce Faci Pentru Mine',
    'perform_build_free': 'Execut construcția completă BMW F32 420d Stage 2+ GRATUIT',
    'win_win_partnership': 'Parteneriat Câștig-Câștig',
    'partnership_proposal_desc': 'Aceasta este o propunere de parteneriat unde ambele părți beneficiază în mod egal. Nu se schimbă bani - doar schimb de valoare mutuală.',
    
    // Quote Page - System Features
    'bmw_service_dashboard': 'Dashboard Service BMW',
    'dashboard_desc': 'Sistem complet de management reparații cu urmărire în timp real',
    'client_portal_desc': 'Căutare număr înmatriculare, VIN și specificații vehicul',
    'quote_system': 'Sistem Oferte',
    'quote_system_desc': 'Generare și management automat oferte',
    'bye_auto_website': 'Website BYE Auto',
    'website_desc': 'Website profesional companie cu servicii, opțiuni tuning și sistem rezervări',
    'analytics_reports': 'Analiză & Rapoarte',
    'analytics_desc': 'Intelligence business și urmărire performanță',
    'mobile_application': 'Aplicație Mobilă',
    'mobile_app_desc': 'Aplicații iOS și Android pentru operațiuni teren',
    'api_integration': 'Integrare API',
    'api_desc': 'Integrări terți și sincronizare date',
    'multi_language_support': 'Suport Multi-limbă',
    'multi_lang_desc': 'Suport limbi engleză, română și olandeză',
    'backup_security': 'Backup & Securitate',
    'backup_desc': 'Backup-uri automate și funcții securitate avansate',
    
    // Quote Page - BMW Project
    'vehicle_info': 'Vehicul',
    'vehicle_desc': 'BMW 420d F32 (motor N47, 184 cp stock)',
    'goal_desc': 'Upgrade Stage 2+/3 de încredere la ±270–280 cp / ±580–600 Nm',
    'power': 'Putere',
    'torque': 'Cuplu',
    'acceleration': 'Accelerație',
    'reliability': 'Fiabilitate',
    'budget_note': 'Notă: Prețurile pot varia în funcție de cerințe specifice și condiții de piață',
    
    // Quote Page - System Overview
    'complete_system_overview': 'Prezentare Completă Sistem BYE Auto',
    'admin_dashboard_functions': 'Funcții Dashboard Admin',
    'vehicle_management': 'Management Vehicule (Adaugă, Editează, Șterge)',
    'repair_order_management': 'Management Comenzi Reparații',
    'client_database_history': 'Bază Date Clienți & Istoric',
    'real_time_analytics': 'Analiză & Rapoarte Timp Real',
    'whatsapp_integration': 'Integrare WhatsApp Business',
    'multi_lang_support_dashboard': 'Suport Multi-limbă (EN/RO)',
    'automated_quotes': 'Generare Oferte Automată',
    'inventory_management': 'Management Inventar',
    'website_functions': 'Funcții Website BYE Auto',
    'company_information': 'Informații Companie & Despre',
    'bmw_services': 'Servicii Service & Reparații BMW',
    'tuning_options': 'Opțiuni Tuning Performanță',
    'online_booking': 'Sistem Rezervări Online',
    'license_lookup': 'Instrument Căutare Număr Înmatriculare',
    'contact_form': 'Formular Contact & Locație',
    'customer_reviews': 'Recenzii Clienți & Galerie',
    'mobile_responsive': 'Design Responsive Mobil',
    'tuning_services_integration': 'Servicii Tuning Performanță (Integrare Website)',
    'stage_1_tuning': 'Tuning Stage 1',
    'stage_1_desc': 'Optimizare software pentru hardware stock',
    'stage_2_tuning': 'Tuning Stage 2',
    'stage_2_desc': 'Software + upgrade-uri hardware de bază',
    'stage_3_tuning': 'Tuning Stage 3+',
    'stage_3_desc': 'Construcție performanță completă cu hardware personalizat',
    'power_increase': 'Creștere Putere',

    // Work Management
    'work_management': 'Management Lucrări',
    'workshop_dashboard': 'Dashboard Atelier',
    'remaining_work_hours': 'Ore Lucru Rămase',
    'expected_completion': 'Finalizare Așteptată',
    'overtime_alert': 'Alertă Ore Suplimentare',
    'today': 'Astăzi',
    'normal_time': 'Timp Normal',
    'working_status': 'Status Lucru',
    'working': 'Lucrând',
    'outside_work_hours': 'În Afara Programului',
    'remaining_work': 'Lucru Rămas',
    'expected_finish': 'Finalizare Așteptată',
    'waiting_items': 'Elemente În Așteptare',
    'overtime_needed': 'Ore Suplimentare Necesare',
    'overtime_until': 'Ore Suplimentare Până La',
    'plan_extra_time': 'Planifică Timp Suplimentar!',
    'on_schedule': 'Pe Program',
    'no_overtime_needed': 'Nu Sunt Necesare Ore Suplimentare',
    'total_work': 'Lucru Total',
    'ready': 'Gata',
    'in_progress': 'În Curs',
    'team': 'Echipa',
    'tasks': 'sarcini',
    'efficiency': 'Eficiență',
    'average_time': 'Timp Mediu',
    'time_saved': 'Timp Economisit',
    'customer_satisfaction': 'Satisfacția Clienților',
    'pending': 'În Așteptare',
    'assigned_to': 'Atribuit La',
    'estimated_time': 'Timp Estimativ',
    'started_at': 'Început La',
    'work_type': 'Tip Lucru',
    'new_task': 'Sarcină Nouă',
    'edit_task': 'Editează Sarcină',
    'delete_task': 'Șterge Sarcină',
    'start': 'Începe',
    'finish': 'Finalizează',
    'restart': 'Repornește',
    'back': 'Înapoi',
    'add': 'Adaugă',
    'select_team_member': 'Selectează Membru Echipă',
    'estimated_time_placeholder': 'ex. 2h',
    'confirm_delete': 'Ești sigur că vrei să ștergi această sarcină?',

    // Opening Hours
    'opening_hours': 'Program de Funcționare',
    'business_hours': 'Program de Lucru',
    'set_all_days': 'Setează Toate Zilele 08:00-18:00',
    'weekdays_only': 'Doar Zile Lucrătoare',
    'close_all_days': 'Închide Toate Zilele',
    'save_opening_hours': 'Salvează Programul',
    'closed': 'Închis',
    'monday': 'Luni',
    'tuesday': 'Marți',
    'wednesday': 'Miercuri',
    'thursday': 'Joi',
    'friday': 'Vineri',
    'saturday': 'Sâmbătă',
    'sunday': 'Duminică',

    // Work Hours & Overtime
    'work_end_time': 'Timp Finalizare',
    'overtime_required': 'Ore Suplimentare Necesare',
    'work_until': 'Lucru Până La',
    'hours_overtime': 'ore suplimentare',
    'today_schedule': 'Programul de Astăzi',

    // Common
    'close': 'Închide',
    'logout': 'Deconectare',
    'language': 'Limbă',
    'english': 'Engleză',
    'romanian': 'Română'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ro')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 